version: '3.9'

x-volumes:
  - &project .:/var/www/
  - &project-ro .:/var/www/:ro
  - &ssh ~/.ssh/:/root/.ssh/:ro

services:
  web:
    container_name: ${APP_NAME}-web
    image: nginx:1.24-alpine
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      - TZ=${TZ}
    volumes:
      - *project-ro
      - ./docker/conf/nginx:/etc/nginx/conf.d:ro
      - ./docker/conf/ssl:/etc/nginx/ssl:ro
      - ./docker/logs/nginx:/var/log/nginx
    restart: on-failure
    depends_on:
      - php

  php:
    container_name: ${APP_NAME}-php
    image: docker.kelnik.pro/php/php-fpm:8.2
    environment:
      - TZ=${TZ}
    volumes:
      - *project
      - *ssh
#      - ./docker/logs/php:/var/log/php
    restart: on-failure
    user: developer:developer
    working_dir: /var/www
    depends_on:
     - mailpit
     - chromium
#      - db
#      - redis
#      - memcached

  node:
    container_name: ${APP_NAME}-node
    image: docker.kelnik.pro/nodejs/node:18
    ports:
      - ${BROWSER_SYNC_WEB_PORT:-8080}:8080
      - ${BROWSER_SYNC_UI_PORT:-3001}:3001
      - ${VUE_SERVER_PORT:-3000}:3000
    volumes:
      - *project
      - *ssh
    environment:
      - NODE_ENV=${NODE_ENV:-'development'}
    user: node:node
    command: nodejs /home/node/http_server.js
    working_dir: /var/www
    restart: on-failure

  db:
    container_name: ${APP_NAME}-db
    image: mariadb:10.5.8
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./docker/data/db:/var/lib/mysql
      - ./docker/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql
    restart: on-failure

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:6-alpine
    volumes:
      - ./docker/data/redis:/data

#  memcached:
#    container_name: ${APP_NAME}-memcached
#    image: memcached:alpine

  chromium:
    container_name: ${APP_NAME}-chromium
    image: nextnextools/chromium:110
    environment:
      - TZ=${TZ}
    volumes:
      - ./docker/data/chromium:/home/chromium/.fonts

  mailpit:
    container_name: ${APP_NAME}-mailpit
    image: axllent/mailpit:v1.6.10
    ports:
#      - 1025:1025
      - 8025:8025

networks:
  default:
    name: ${APP_NAME}-network
